(ns rtl.waveform
  "Waveform view and IEEE 1364 VCD export. Restored from kami-rtl's
  `waveform` module (deleted PR #82).")

(def display-formats #{:binary :hex :decimal :analog})

(defn waveform-signal [{:keys [name width transitions display-format color]}]
  {:name name :width width :transitions transitions
   :display-format display-format :color color})

(defn waveform-view
  "A fresh, empty waveform view."
  []
  {:signals [] :time-range [0 0] :cursor-time 0 :zoom 1.0})

(defn add-signal
  "Add `signal` to the view, extending `:time-range`'s end if `signal`'s
  last transition is later."
  [view signal]
  (let [last-t (first (last (:transitions signal)))
        [t0 t1] (:time-range view)
        t1 (if (and last-t (> last-t t1)) last-t t1)]
    (-> view (assoc :time-range [t0 t1]) (update :signals conj signal))))

(defn- vcd-id
  "A VCD identifier from `index` (printable ASCII 33-126, wrapping)."
  [index]
  (str (char (+ 33 (mod index 94)))))

(defn- format-vcd-value
  "A single VCD value-change line for a scalar (`<value><id>`) or vector
  (`b<bits> <id>`) signal."
  [width val id]
  (if (= width 1)
    (str (or (first val) "x") id "\n")
    (str "b" val " " id "\n")))

(defn export-vcd
  "Export `signals` to IEEE 1364 Value Change Dump (VCD) format: header,
  variable definitions, initial `$dumpvars`, then time-ordered value changes."
  [signals]
  (let [header (str "$date\n  Generated by KAMI RTL\n$end\n"
                     "$version\n  KAMI RTL 0.1.0\n$end\n"
                     "$timescale\n  1ns\n$end\n")
        var-defs (str "$scope module top $end\n"
                       (apply str
                              (map-indexed
                               (fn [i sig] (str "$var wire " (:width sig) " " (vcd-id i) " " (:name sig) " $end\n"))
                               signals))
                       "$upscope $end\n"
                       "$enddefinitions $end\n")
        initial (str "$dumpvars\n"
                      (apply str
                             (map-indexed
                              (fn [i sig]
                                (let [id (vcd-id i)]
                                  (if-let [[_ val] (first (:transitions sig))]
                                    (format-vcd-value (:width sig) val id)
                                    (if (= (:width sig) 1)
                                      (str "x" id "\n")
                                      (str "bx " id "\n")))))
                              signals))
                      "$end\n")
        all-changes (->> (map-indexed (fn [i sig] (map (fn [[t v]] [t i v]) (:transitions sig))) signals)
                          (mapcat identity)
                          (sort-by (fn [[t i _]] [t i])))
        changes (loop [remaining all-changes current-time nil out ""]
                  (if (empty? remaining)
                    out
                    (let [[t idx val] (first remaining)
                          out (if (not= current-time t) (str out "#" t "\n") out)
                          id (vcd-id idx)
                          out (str out (format-vcd-value (:width (nth signals idx)) val id))]
                      (recur (rest remaining) t out))))]
    (str header var-defs initial changes)))
